//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace treker_sna_001
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journal
    {
        public int Id { get; set; }
        public int UserIdUser { get; set; }
        public string TypeDream { get; set; }
        public string Feelings { get; set; }
        public int WakeUpCount { get; set; }
        public System.DateTime TimeDown { get; set; }
        public System.DateTime TimeWakeUp { get; set; }
        public string Stress { get; set; }
        public string Phisical { get; set; }
        public string Temperature { get; set; }
    
        public virtual User User1 { get; set; }
    }
}
