
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace treker_sna_001
{

using System;
    using System.Collections.Generic;
    
public partial class WakeUpper
{

    public int Id { get; set; }

    public int UserIdUser { get; set; }

    public System.DateTime dateTime { get; set; }

    public string Occasion { get; set; }



    public virtual User idUser { get; set; }

}

}
